sonar.projectKey=worker-services-consumer
sonar.projectName=Worker Services Consumer
sonar.working.directory=C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer
sonar.pullrequest.cache.basepath=C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer
sonar.sources=\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\sonar-analysis.ps1"

488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.projectKey=worker-services-consumer:488D46D1-C125-454E-A2E5-02F12EDAE4CC
488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.projectName=Worker_Services_Consumer
488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.projectBaseDir=C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer
488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.sourceEncoding=utf-8
488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.tests=
488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.sources=\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Configuration\\KafkaSettings.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Configuration\\WorkerSettings.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Models\\LogMessage.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Program.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Services\\DatabaseService.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Services\\IDatabaseService.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Services\\IKafkaConsumerService.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Services\\KafkaConsumerService.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Services\\ServiceBase.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Worker.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\obj\\Debug\\net8.0\\Worker_Services_Consumer.GlobalUsings.g.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\obj\\Debug\\net8.0\\Worker_Services_Consumer.AssemblyInfo.cs",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\appsettings.Development.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\appsettings.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\Properties\\launchSettings.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\obj\\project.assets.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\obj\\Worker_Services_Consumer.csproj.nuget.dgspec.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\bin\\Debug\\net8.0\\Worker_Services_Consumer.deps.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\bin\\Debug\\net8.0\\Worker_Services_Consumer.runtimeconfig.json",\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\Worker_Services_Consumer\\obj\\Debug\\net8.0\\Worker_Services_Consumer.sourcelink.json"

488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.cs.analyzer.projectOutPaths=\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\.sonarqube\\out\\0"
488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.cs.roslyn.reportFilePaths=\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\.sonarqube\\out\\0\\Issues.json"
488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.cs.scanner.telemetry=\
"C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\.sonarqube\\out\\0\\Telemetry.json"

488D46D1-C125-454E-A2E5-02F12EDAE4CC.sonar.working.directory=C:\\UCR_2025\\Segundo_Semestre\\InfoAplicada\\Proyecto\\Worker_Services_Consumer\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=488D46D1-C125-454E-A2E5-02F12EDAE4CC

